levels = {
        "Приветствие и прощание":{
           "Tere hommikust": "Доброе утро",
            "Tere õhtust": "Добрый вечер",
            "Tere päevast": "Добрый день",
            "Tere": "Здравствуйте",
            "Head aega": "До свидания",
            "Nägemist": "До встречи",
            "Homseni": "До завтра",
            "Head õhtut": "Хорошего вечера",
            "Kõike head": "Всего хорошего",
            "Kuulmiseni": "Услышимся",
            "Head ööd": "Спокойной ночи", 
    },

        "Благодарность и извинение":{
            "Aitäh": "Спасибо",
            "Palun": "Пожалуйста",
            "Suur tänu": "Большое спасибо",
            "Pole tänu väärt": "Не за что",
            "Suur aitäh": "Большое спасибо",
            "Palun vabandust": "Прошу прощения",
            "Vabandust": "Извините",
            "Pole viga": "Ничего страшного",
            "Anna andeks": "Извини",
    },

        "Название дней недели, месяцев":{
            "Esmaspäev": "Понедельник",
            "Teisipäev": "Вторник",
            "Kolmapäev": "Среда",
            "Neljapäev": "Четверг",
            "Reede": "Пятница",
            "Laupäev": "Суббота", 
            "Pühapäev": "Воскресенье",
            "Jaanuar": "Январь",
            "Veebruar":  "Февраль",
            "Märts": "Март",
            "Aprill": "Апрель",
            "Mai": "Май",
            "Juuni": "Июнь",
            "Juuli": "Июль",
            "August": "Август",
            "September": "Сентябрь",
            "Oktoober": "Октябрь",
            "November": "Ноябрь",
            "Detsember": "Декабрь",
    },
        "Время и цифры":{
            "Mis kell on": "Сколько времени",
            "Kell on pool seitse": "Полседьмого",
            "Kui palju kell on": "Который час",
            "Veerand kolm": "Четверть третьего",
            "Kell on juba kolmveeranоd kaksteist": "Без пятнадцати двенадцать",
            "Üks": "Один",
            "Kaks": "Два",
            "Kolm": "Три",
            "Neli": "Четыре",
            "Viis": "Пять",
            "Kuus": "Шесть",
            "Seitse": "Семь",
            "Kaheksa": "Восемь",
            "Üheksa": "Девять",
            "Kümme": "Десять",
            "Üksteist": "Одиннадцать",
            "Kaksteist": "Двенадцать",
    },
        "Знакомство":{
            "Saame tuttavaks": "Давайте знакомиться",
            "Mis su nimi on?": "Как вас зовут?",
            "Mina olen Artjom": "Я Артём",
            "Saage palun tuttavaks": "Пожалуйста, познакомьтесь",
            "Väga meeldiv": "Очень приятно",
            "Mina ei ole Anton": "Я не Антон",
            "Me pole vist varem kohtunud": "Мы, кажется, раньше не встречались",
            "Meeldiv tutvuda": "Приятно познакомится",
            "Vabandust, ma ei kuulnud sind": "Извините, я не расслышал",
    },
        "Вы говорите по-эстонски?":{
            "Kas sa räägid eesti keelt?": "Ты говоришь по-эстонски?",
            "Räägin küll": "Я говорю",
            "Ei räägi": "Не говорю",
            "Natukene": "Немного",
            "Ei, kahjuks ei oska": "К сожалению не владею",
            "Kas te oskate eesti keelt?": "Вы владеете эстонским языком?",
            "Oskan küll": "Да, владею",
            "Tõesti?": "Неужели?",
            "Kui huvitav!": "Как любопытно!",
    },
        "Где ты живешь?":{
            "Kus sa oled?": "Где ты?",
            "Kus sa elad?": "Где ты живешь?",
            "Kesklinnas": "В центре города",
            "Mis su aadress on?": "Какой у тебя адрес?",
            "Ma viin su ära": "Я подвезу тебя",
            "Ma elan nüüd Mustamäel": "Я теперь живу в Мустамяэ",
            "Ma olen hetkel Soomes": "Я сейчас в Финляндии",
            "Väga vahva": "Очень здорово!",
            "Ei, ma olen veel Venemaal.": "Нет, я еще в России.",
            "Mina ka": "Я тоже",
            "Kas sa oled juba Eestis?": "Ты уже в Эстонии?",
            "Ma olen praegu Tallinnas": "Я сейчас в Таллинне",
        }
}